apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwgvgt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwgvgt
  template:
    metadata:
      labels:
        app: qwgvgt
    spec:
      containers:
      - image: okteto.dev/qwgvgt:latest
        name: qwgvgt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/GoidFood-html.zip"
        - name: Vless_UUID
          value: "47744963-c822-4fc9-b9bd-45318e087e0c"
        - name: Vless_Path
          value: "/47744963-c822-4fc9-b9bd-45318e087e0c-vless"
        - name: Vmess_UUID
          value: "47744963-c822-4fc9-b9bd-45318e087e0c"
        - name: Vmess_Path
          value: "/47744963-c822-4fc9-b9bd-45318e087e0c-vmess"
        - name: Share_Path
          value: "/vn1k"
